src/layout/index.tsx
feat: test pr template works now!
123123
No
=> feat: test pr template

.eslintrc.cjs, .husky/pre-commit, package-lock.json, src/components/atoms/Backdrop/index.tsx, src/components/atoms/Icon/Check.tsx, src/components/atoms/Icon/SmallRectangle.tsx, src/components/atoms/Icon/index.tsx, src/components/atoms/Rectangle/index.tsx, src/components/atoms/Seat/index.tsx, src/components/organisms/Form/index.tsx, src/components/organisms/Timeline/index.tsx
=> feat: add pre commit build, fix ts runtime error

src/pages/Login/index.tsx
fix Loginpage
https://trello.com/c/fp9cusG4/73-feuser-login
=> fix: login page view

src/components/atoms/Breadcrumb/index.tsx, src/components/molecules/Figure/index.tsx, src/pages/Detailartikel/index.tsx, src/routes/routes.tsx
=> feat: add detail artikel page

src/components/molecules/Figure/index.tsx, src/pages/Detailartikel/index.tsx
Adding Article Detail page
https://trello.com/c/8XTHAEx2/6-fswuser-halaman-detail-artikel
no it doesnt breaking change
=> feat: detail artikel

index.html, src/components/atoms/Button/index.tsx, src/pages/Login/index.tsx
Add Toggle show password and Email validation
-
no
=> fix: add show password & email validation

src/components/atoms/Breadcrumb/index.tsx, src/pages/TentangKami.tsx, src/routes/routes.tsx
In this pull request, I have added a new "Tentang Kami" page, which is now responsive. Additionally, I improved the responsiveness of the Breadcrumb component. In my opinion, the Navbar or footer might still need adjustments for responsiveness
https://trello.com/c/52t4HC62/11-fswuser-tentang-kami
[No]
=> feat: add Tentang Kami Page - responsive

src/components/atoms/Breadcrumb/index.tsx, src/pages/TentangKami.tsx
Fix my changes on breadcrumbs
No
=> fix: fix BreadCrumb

src/pages/TentangKami.tsx
Fixing bug in layout > 1440px
No
=> fix: fix layout page in 2560px with 12 grid system

src/constants/common.ts, src/pages/Artikel/index.tsx, src/pages/TentangKami/index.tsx
I added a Title, Subtitle, and 4 filter buttons in the hero section on the Artikel page. Then, I implemented slider functionality and adjusted the responsiveness of the Artikel page. I also made some refinements to the hero section for the Tentang Kami page.
https://trello.com/c/SXu9rNac/5-fswuser-halaman-artikel
No
=> fix: Artikel Page & Tentang Kami Page

package.json, src/pages/OtpField/index.tsx, src/pages/OtpField/modal.tsx, src/pages/OtpField/otp.hooks.tsx, src/pages/Register/index.tsx, src/pages/Register/register.hooks.tsx, src/state/userSlice/userData.store.ts
=> feat: integration register, resend otp, otp verify

src/pages/Artikel/index.tsx, src/pages/PusatBantuan/index.tsx, src/pages/TentangKami/index.tsx, src/routes/routes.tsx
I created the Help Center page and made it responsive. I also made some minor adjustments to the Article and About Us pages, focusing on text coloration.
https://trello.com/c/YuHzTrlM/45-fsw-pusat-bantuan
No
=> feat: add Pusat Bantuan page

src/pages/OtpField/otp.hooks.tsx, src/pages/Register/register.hooks.tsx
=> fix: base url api register

.env.example, src/services/axios.ts
Just change the API URL use meta env from @fitridra 
No
=> fix: api url

src/routes/routes.tsx
=> refactor: route terms of service

src/components/atoms/Seat/index.tsx, src/routes/routes.tsx
Fix bugs on choose seat feature
https://trello.com/c/nzk5AQtA
- [✅ ] I have performed a self-review of my code
It doesn't have breaking change
=> fix: fixed bug on choose seat feature

src/components/atoms/Seat/index.tsx, src/components/organisms/PopUp/detailTicket.tsx, src/components/organisms/SeatModal/index.tsx
Modified get params for seat.
https://trello.com/c/nzk5AQtA
Doesn't have breaking change
=> fix: modified params to fetch seat from API

src/pages/Artikel/index.tsx, src/pages/ArtikelKuliner/index.tsx, src/pages/ArtikelTerbaru/index.tsx, src/pages/ArtikelWisata/index.tsx, src/pages/Detailartikel/index.tsx, src/routes/routes.tsx
=> feat(article-integration): integration

src/components/organisms/FilterHome/index.tsx, src/pages/Admin/Analitik/index.tsx, src/routes/routes.tsx
=> home jumlah penumpang

src/components/organisms/Admin/Sidebar.tsx, src/components/organisms/CardTicket.tsx, src/components/organisms/Dropdown/index.tsx, src/components/organisms/FilterHome/index.tsx, src/components/organisms/Notification/index.tsx, src/pages/FullSearchTickets.tsx, src/usecases/common/useDateFormat.ts
Fix Card ticket, fix Hour format
=> fix: card ticket

src/components/organisms/SeatLists/helpers/index.tsx, src/components/organisms/SeatModal/index.tsx
Fix bug on booked seats from API.
https://trello.com/c/nzk5AQtA
Doesn't have breaking change
=> fix: fix bug on booked seat from API

src/components/organisms/CardTicket.tsx, src/components/organisms/Order/index.tsx, src/components/organisms/Summary/index.tsx, src/pages/FullSearchTickets.tsx, src/usecases/common/useDateFormat.ts
=> fix: checkout modal

src/components/atoms/Breadcrumb/index.tsx, src/components/molecules/Sidebar/index.tsx, src/components/organisms/CardPayment/index.tsx, src/components/organisms/CardTicket.tsx, src/components/organisms/Dropdown/index.tsx, src/components/organisms/FilterHome/index.tsx, src/components/organisms/ForgotPassword/ModalPopupConfirm.tsx, src/components/organisms/Form/index.tsx, src/components/organisms/Invoice/index.tsx, src/components/organisms/Navbar/index.tsx, src/components/organisms/Navbar/navbar.hooks.tsx, src/components/organisms/Order/index.tsx, src/components/organisms/PopUp/Loading.tsx, src/components/organisms/PopUp/PopUpCheckout.tsx, src/components/organisms/PopUp/SeatModal.tsx, src/components/organisms/PopUp/confirmPayment.tsx, src/components/organisms/PopUp/detailTicket.tsx, src/components/organisms/PopUp/modalLogout.tsx, src/components/organisms/SeatLists/index.tsx, src/components/organisms/Steps/index.tsx, src/components/organisms/Summary/index.tsx, src/pages/Admin/Ticket/modalCreate.tsx, src/pages/Admin/Ticket/modalEdit.tsx, src/pages/Checkout/index.tsx, src/pages/ListSeat/dummy.tsx, src/state/seatSlice/slice.tsx
fix checkout responsive, add Logout popup, and add id
=> fix: checkout Responsive and add id

src/components/organisms/Invoice/AndroidInvoice.tsx, src/components/organisms/SeatLists/index.tsx, src/routes/routes.tsx
Added id attribute on each seat and modified invoice page for android.
Does not have breaking change.
=> fix: added id attribute on seat and modified invoice for android

src/components/molecules/Sidebar/index.tsx, src/components/organisms/NotificationPage/index.tsx, src/components/organisms/Profil/index.tsx, src/components/organisms/Profil/profile.hooks.tsx, src/components/organisms/Riwayat/index.tsx, src/components/organisms/Riwayat/riwayat.hooks.tsx, src/components/organisms/Riwayat/riwayatbyid.tsx, src/components/organisms/Riwayat/timeline.tsx, src/components/organisms/SeatLists/index.tsx, src/layout/UserDashboard.tsx, src/pages/Riwayat/riwayatbyid.tsx, src/routes/routes.tsx, src/services/api.ts, src/usecases/common/useDateFormat.ts
=> feat: detail history order
